In [6]:
import numpy as np

arr1 = np.array([2,3,4])
arr2 = np.array([3,5,3])

arr3 = arr1 * arr2

arr3

array([ 6, 15, 12])

In [9]:
import numpy as np
a = np.array([[0, 0, 0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([1, 2, 3])
c = a + b
print(c)

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [10]:
a = np.array([[0, 0, 0],
              [10, 10, 10],
            ])
b = np.array([1, 2, 3])
c = a + b
print(c)

[[ 1  2  3]
 [11 12 13]]


In [13]:
a = np.array([[0, 0, 0],
              [10, 10,9],
            ])
b = np.array([1, 2, 3])
c = a + b
print(c)

[[ 1  2  3]
 [11 12 12]]


In [15]:
A = np.array([[1, 2, 3], [1, 2, 3]])
print(A)
b = np.array([1, 2, 3])
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]
