In [11]:
import numpy as np

In [12]:
my_arr = np.arange(1000000)

In [13]:
my_list = list(range(1000000))

In [14]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 15.6 ms
Wall time: 13.3 ms


In [16]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 516 ms
Wall time: 521 ms


In [17]:
data = np.random.randn(2, 3)

In [18]:
data

array([[-0.29242576,  0.15238015, -0.70236896],
       [ 1.19025381, -2.73979111, -0.6455288 ]])

In [19]:
data * 10

array([[ -2.92425763,   1.52380155,  -7.02368964],
       [ 11.9025381 , -27.39791109,  -6.45528798]])

In [20]:
data + data

array([[-0.58485153,  0.30476031, -1.40473793],
       [ 2.38050762, -5.47958222, -1.2910576 ]])

In [21]:
data.shape

(2, 3)

In [22]:
data.dtype

dtype('float64')

In [23]:
data1 = [2, 3.4, 5, 0, 1]

arr1 = np.array(data1)


arr1

array([2. , 3.4, 5. , 0. , 1. ])

In [27]:
data2 = [[3, 4, 5, 2],[3, 4, 5, 3],[3, 4, 6, 5]]

arr2 = np.array(data2)

arr2

array([[3, 4, 5, 2],
       [3, 4, 5, 3],
       [3, 4, 6, 5]])

In [28]:
arr2.shape

(3, 4)

In [29]:
arr2.ndim

2

In [32]:
zeroArray = np.zeros(10)
zeroArray

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
zeroArray.dtype

dtype('float64')

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
arr = np.array([1, 2, 3, 4, 5])

arr.dtype

dtype('int32')

In [38]:
float_arr = arr.astype(np.float64)

In [39]:
float_arr

array([1., 2., 3., 4., 5.])

In [40]:
float_arr.dtype

dtype('float64')

In [41]:
arr = np.array([[1., 2., 3.], [4., 5., 6. ]])

In [42]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [43]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [44]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [45]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
arr2 = np.array([[0., 4., 1. ],[3., 5., 7.]])

In [48]:
arr2 > arr

array([[False,  True, False],
       [False, False,  True]])

In [49]:
arr = np.arange(10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr[5]

5

In [52]:
arr[5:8]

array([5, 6, 7])

In [58]:
arr[5:6]  = 12

In [59]:
arr

array([ 0,  1,  2,  3,  4, 12,  6,  7,  8,  9])