In [3]:
#dot()
import numpy as np  
a = np.array([[13,20],[2,8]])  
b = np.array([[6,0],[3,99]])  
dot = np.dot(a,b)  
print(dot)  

[[ 138 1980]
 [  36  792]]


In [5]:
#vdot()
a = np.array([[13,20],[2,8]])  
b = np.array([[6,0],[3,99]])  
vdot = np.vdot(a,b)  
print(vdot)  

876


In [6]:
#matmul()
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  
b = np.array([[1,2,3],[4,5,6],[7,8,9]])  
mul = np.matmul(a,b)  
print(mul) 

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [7]:
#det()
a = np.array([[1,2],[3,4]])  
print(np.linalg.det(a))  

-2.0000000000000004


In [8]:
arr= np.array([[1,23,78],[98,60,75],[79,25,48]])  
print(arr)
#Minimum Function
print(np.amin(arr))
#Maximum Function
print(np.amax(arr))

[[ 1 23 78]
 [98 60 75]
 [79 25 48]]
1
98


In [9]:
a = np.array([5,6,7]) 
print(a)
print(np.mean(a))


[5 6 7]
6.0


In [10]:
a = np.array([5,6,7]) 
print(a)
print(np.median(a))


[5 6 7]
6.0


In [11]:
a = np.array([5,6,7]) 
print(a)
print(np.std(a))


[5 6 7]
0.816496580927726


In [12]:
a = np.array([5,6,7]) 
print(a)
print(np.var(a))

[5 6 7]
0.6666666666666666


In [13]:
a = np.array([5,6,7]) 
print(a)
#without weight same as mean
print(np.average(a))
#with weight gives weighted average
wt = np.array([8,2,3])
print(np.average(a, weights=wt))

[5 6 7]
6.0
5.615384615384615
